language: node_js
node_js:
  - "0.10"
before_install:
  - cd && pwd && ll
  - git clone https://github.com/uikit/uikit.git uikit && ll
  - npm install -g grunt-cli
script:
  - mkdir -p uikit/themes/custom
  - export
  - cp -r ${TRAVIS_REPO_SLUG} uikit/themes/custom/tsv
  - cd uikit
  - npm install
  - grunt