language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
script:
  - git clone https://github.com/uikit/uikit.git uikit
  - cd uikit
  - npm install
  - mkdir -p themes/custom
  - cp -r $TRAVIS_REPO_SLUG themes/custom/tsv
  - grunt